[addnotif] 공지사항 추가
junglesub/CRA-Project-T pull request #23
Opened 2021-01-28 09:49 UTC by achel003

일단은 전달받은 정보가 아닌 있는 정보에서 useeffect안에 firebase를 사용해서 그룹이름을 가져왔고 회원 정보를 가져와 공지사항 화면 만듦

2021-02-02 09:17 UTC, junglesub requested changes
수정 및 확인사항 확인해주세요.

2021-02-02 09:17 UTC, junglesub commented on functions/package.json
> +    "kill-port": "^1.6.1",
`yarn remove kill-port` 를 활용해서 삭제해주세요

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +            groups: admin.firestore.FieldValue.arrayUnion(groupID),
`users` 에 그룹 정보를 저장할때 `groups` 를 사용했습니다.

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    if (!userData.group)
위에서 말한 것처럼 `users` 정보에는 `groups` 를 이용하셨기때문에 groups 으로 바꿔주세요.

```suggestion
    if (!userData.groups)
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +        .json({ status: 403, error: "USERGROUP FORBIDDEN", uid });
권한이 없는 것이 아닌 존재하지 않는 것이기 때문에 빈 그룹 정보인 `[]` 같은 것을 반환해야할 것 같습니다. 
403 을 반환할경우 Frontend 에 추가적인 불필요한 Error handling 을 해야합니다.

```suggestion
        .json({ status: 200, [] });
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +        admin.firestore().collection("group").doc(groupID).delete();
`groups` 가 맞습니다.

```suggestion
        admin.firestore().collection("groups").doc(groupID).delete();
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +      data: userData.group, // Group ID
```suggestion
      data: userData.groups, // Group ID
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +        today,
`admin.firestore.Timestamp.fromDate(new Date());`

```suggestion
        created: admin.firestore.Timestamp.fromDate(new Date()),
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +  if (!announceName || !description || !wayofannounce || !checked || !today) {
서버에서 날짜를 추가하기에 데이터를 받을 필요 없다.

```suggestion
  if (!announceName || !description || !wayofannounce || !checked) {
```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    today,
```suggestion

```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +  // 유효성 #추가??
wayofannounce 가 정의되어 있음. 근데 이게 정의되어 있는 옵션중 하나인지 확인.

```javascript
  // 유효성 #2 - type 이 club, association, others
  if (!["club", "association", "others"].includes(type)) {
    return res.status(221).json({
      status: 221,
      error: "알 수 없는 type",
    });
  }
```
위 참고

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    }
announcement 에 추가하기 전에 
`checked` 배열에 있는 uid들이 `groupdata.members` 포함되어 있는지 확인. 그리고 만약에 하나라도 포함이 안되어있으면 `400 오류` 출력.

2021-02-02 09:17 UTC, junglesub commented on src/App.jsx
> +        //console.log("Snapshot Triggered");
이거 왜 주석처리?

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +const userId = "C62F1D8OsnZtSzFhZMR8EPusrYm1";
지금은 현재 그룹 아이디와 유저아이디가 고정되어있는 상태 이것을 현제 로그인되어있는 유저와 유저가 선택한 그룹으로 지정되게 변경

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  const currentUserId = "uid1"; // 이후 uid7을 이용해 추가확인
사용하지 않는 변수

```suggestion

```

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  console.log(userDataStore);
최종 커밋 전에는 삭제해주세요.
```suggestion

```

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  const today = new Date().toLocaleString();
얘도 사용하지 않을 예정이기 때문에 삭제해주세요.
```suggestion

```

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +    today: today,
삭제

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +          .get(`/group/${groupId}/members`, {
고정된 `groupId` 가 아닌 유저가 직접 선택할 수 있도록

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  // }
주석처리 필요한것만 냅두고 삭제해주세요

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  // }, []);
주석처리 필요한것만 냅두고 삭제해주세요

2021-02-02 09:17 UTC, junglesub commented on functions/src/middlewares/checkAuth.ts
> +  console.log(token);
디버깅 할때 썼든것이므로 삭제해주세요.
```suggestion

```

2021-02-02 09:17 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    }
```javascript
const requested_list = ["a", "b", "c", "d"];
const server_list = ["b", "c", "d", "e"];

// https://github.com/cra-project-t/CRA-Project-T/pull/23/files#diff-67c9c52abe967a749406767bbece98c8a746a333d1edd56a7e4abfd6ae58ebdfR372-R374
// 서버측 멤버 (server_list)에 요청된 멤버 (requested_list)의 "a" 가 미포함
console.log(
  requested_list.filter((member) => server_list.indexOf(member) === -1)
);
// => ['a'] - 따라서 a 가 미포함 되었다는 것을 알려줌 누가 미포함인지 에러로 알려주기만 하면 끝
```
이거 참고해서 하면 될 것 같습니다.

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +  // }, []);
여기도 필요없는 코드면 삭제

2021-02-02 09:17 UTC, junglesub commented on src/components/AddNotif.jsx
> +              ) -> 이거 공지사항 글 쓸때마다 render됨. 돈 펑펑펑
????

2021-02-02 10:19 UTC, achel003 commented on functions/src/routers/groupRouter.ts
> +        .json({ status: 403, error: "USERGROUP FORBIDDEN", uid });
Error handling이라는 것이 Frontend에서 try catch(e)할때의 catch(e)인가요?

2021-02-02 10:22 UTC, achel003 commented on functions/src/routers/groupRouter.ts
> +    }
```
if((checked.filter((member)=>groupdata.members.indexOf(member)===-1))){
      return res.sendStatus(400);
    }
```
이렇게 하면 되나요?

2021-02-02 10:23 UTC, achel003 commented on src/components/AddNotif.jsx
> +const userId = "C62F1D8OsnZtSzFhZMR8EPusrYm1";
언제요?

2021-02-02 10:26 UTC, achel003 commented on src/components/AddNotif.jsx
> +              ) -> 이거 공지사항 글 쓸때마다 render됨. 돈 펑펑펑
예압

2021-02-02 10:29 UTC, achel003 commented on functions/src/routers/groupRouter.ts
> +        .json({ status: 403, error: "USERGROUP FORBIDDEN", uid });
그리고 
```
if (!userData.groups){
      return res
        .status(200)
        .json({ status: 200, [] })}
```
vscode로 보았을 때 해당 부분에서 ]}여기에 오류 뜹니다

2021-02-02 10:35 UTC, achel003 commented on functions/src/routers/groupRouter.ts
> +        .json({ status: 403, error: "USERGROUP FORBIDDEN", uid });
<img width="402" alt="addnotify error" src="https://user-images.githubusercontent.com/74362214/106588084-b9fb9980-658d-11eb-9e3a-9fca435489a3.PNG">

Expression expected .랑 저겁니다.

2021-02-02 10:37 UTC, achel003 commented on functions/src/routers/groupRouter.ts
> +    }
<img width="493" alt="addnotify error2" src="https://user-images.githubusercontent.com/74362214/106588299-f5966380-658d-11eb-935b-bda8d00c2d9d.PNG">

member가 map에서의 value같은 역할 아닌가요? 왜 다음과 같은 오류가 뜨는지 모르겠습니다.

2021-02-02 12:30 UTC, junglesub requested changes
수정해오세요

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +      return res.status(200).json({ status: 200, [] })
```suggestion

```
이거 지우고

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +      data: userData.groups, // Group ID
```suggestion
      data: userData.groups || [], // Group ID
```
이런식으로 `||` 을 활용해서 정의가 안되어있으면 빈 배열을 출력하도록

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    created = admin.firestore.Timestamp.fromDate(new Date()),
이렇게 하시면서 선생님, 이거는 기본값이기 때문에 포스트맨이나 그런걸로 `created` 라는 항목을 보내면 덮어씌우기가 된다구요!!!

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +  if (!announceName || !description || !wayofannounce || !checked || !created) {
```suggestion
  if (!announceName || !description || !wayofannounce || !checked) {
```
지우고

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +    }
`member: string`

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +        created,
```suggestion
        created: admin.firestore.Timestamp.fromDate(new Date()),
```

2021-02-02 12:30 UTC, junglesub commented on functions/src/routers/groupRouter.ts
> +        created,
이런식으로 으이?

2021-02-02 12:32 UTC, junglesub commented
@achel003 Conflict 알아서 해결해오세요

2021-02-06 16:56 UTC, junglesub approved these changes

2021-02-06 16:56 UTC, merged