Status를 추가해 정보를 입력받고, Login을 수정해 데이타베이스를 확인할 준비를 함
junglesub/CRA-Project-T pull request #6
Opened 2021-01-22 11:13 UTC by Lee-sehyun

Status를 추가해 정보를 입력받고, Login을 수정해 데이타베이스를 확인할 준비를 함

state라는 배열에 각각의 정보를 저장해놓았음. (console.log는 아직 삭제를 안함.)
전공, 닉네임, 주소 등을 넣어서 저장할 수 있음.(순서는 피드백때 할 예정)
정보를 저장하려고 할때 누를 버튼도 구현해 놓음.

문제점.
Login에서 조건문을 통해서 바로 Status로 넘어가거나, Homepage로 가거나 하고 싶은데, 방법을 잘 모르겠음.

2021-01-22 11:20 UTC, junglesub commented on src/App.jsx
> +              <Route path="/status" exact component={Status} />
테스트 하기 위해서 이렇게 테스트 Route 를 만드는게 가장 좋습니다. @achel003 앱에 추가하는것 대신 이런 식으로 Route 를 추가해주세요.

2021-01-22 11:29 UTC, Lee-sehyun commented on src/App.jsx
> +              <Route path="/status" exact component={Status} />
그 내가 한 것처럼 route를 추가해서 한게 맞다는 얘기지?

2021-01-22 12:25 UTC, junglesub reviewed
질문과 수정요청사항이 있습니다.

2021-01-22 12:25 UTC, junglesub commented on src/pages/Status.jsx
> +        if(event.key === 'Enter'){
Enter일때만 반영한 이유가 뭔가요?

2021-01-22 12:25 UTC, junglesub commented on src/pages/Status.jsx
> +        hakbun: firebase.auth().currentUser.email.substr(0, 8),
`firebase.auth().currentUser` - 은 페이지가 처음 로드 됐을때 firebase 가 로딩될때를 감지하기 못하기 때문에 바람직한 방법이 아닙니다. 물론 프로젝트 앱 자체가 Auth로딩되기 전까지는 실행을 안하는 기능이 구현은 되어 있지만 미래에 발생할 수 있는 문제를 방지하기 위해 https://github.com/csfrequency/react-firebase-hooks/tree/1e893b11a41df8618a80ac7964bdf02dcf05735e/auth 여기에 나오는 방식을 이용해주세요.

2021-01-22 12:25 UTC, junglesub commented on src/pages/Status.jsx
> +                        <InputLabel id="major">전공</InputLabel>
한동대에는 1전공 2전공이 있어서 2개다 확인해주세요.

2021-01-22 12:25 UTC, junglesub commented on src/pages/Status.jsx
> +                                <MenuItem value={"게계 제어 공학부"}>게계 제어 공학부</MenuItem>
오타

2021-01-22 12:25 UTC, junglesub commented on src/pages/Status.jsx
> +                                <MenuItem value={"글로벌 리더쉽 학부"}>글로벌 리더쉽 학부</MenuItem>
서버로 전송될 value 에는 공백이 없는게 좋고 기왕이면 영어로 하는게 더 좋을 것 같습니다.

2021-01-22 13:38 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +        if(event.key === 'Enter'){
엔터가 아니면 여러번 불러오기때문에 비효율적이고 엔터가 한번만 실행시킬때 아주 좋을 것 같아서입니다. 추후 중복인증이라든지, mouseout등을 통해 이벤트를 넣을 생각입니다.

2021-01-22 13:39 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +        hakbun: firebase.auth().currentUser.email.substr(0, 8),
네 알겠습니다!

2021-01-22 13:39 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                        <InputLabel id="major">전공</InputLabel>
아하 맞다. 2전공 있었네요!

2021-01-22 13:40 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                                <MenuItem value={"게계 제어 공학부"}>게계 제어 공학부</MenuItem>
앗 ㅋㅋ 게계 제어 ㅋㅋㅋ 확인했습니다! 오타 수정할게요!

2021-01-22 13:40 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                                <MenuItem value={"글로벌 리더쉽 학부"}>글로벌 리더쉽 학부</MenuItem>
영어라,, 확인했습니다....

2021-01-22 13:45 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                                <MenuItem value={"게계 제어 공학부"}>게계 제어 공학부</MenuItem>
수정.

2021-01-22 13:46 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                        <InputLabel id="major">전공</InputLabel>
수정.

2021-01-22 15:28 UTC, Lee-sehyun commented on src/pages/Status.jsx
> +                                <MenuItem value={"글로벌 리더쉽 학부"}>글로벌 리더쉽 학부</MenuItem>
이거 먼저 수정.

2021-01-22 16:16 UTC, junglesub commented on src/pages/Status.jsx
> +        if(event.key === 'Enter'){
아 알겠습니다.

2021-01-22 16:18 UTC, junglesub commented on src/App.jsx
> +              <Route path="/status" exact component={Status} />
네 맞아요!! 좋은 예였습니다.

2021-01-23 12:52 UTC, junglesub requested changes

2021-01-23 12:52 UTC, junglesub commented on src/components/AddStudent.jsx
> +    else firebase.firestore().collection('user').doc(params.uid).set(params);
`users` 입니다.

2021-01-23 12:52 UTC, junglesub commented on src/components/AddStudent.jsx
> +function AddStudent(params) {
Firebase를 이용하기 때문에 작성하는 코드가 짧습니다.`AddStudent.jsx` 파일은 따로 만들 필요가 없다고 생각하는데 어떻게 생각하시나요? 그냥 버튼을 누르면 자동으로 등록되게 만드는것이 더 좋아보입니다.

2021-01-23 12:52 UTC, junglesub commented on src/components/AddStudent.jsx
> +function AddStudent(params) {
그리고 더더욱 이것은 React 컴포넌트가 아닌 그냥 함수 하나를 가지고 있는 파일이라 부적절 하다고 생각합니다. 만약 추후에 같은 함수를 이용 할 것을 대비하고 싶으면 `utils` 폴더를 만들어 주시는 것이 바람직 합니다.

2021-01-23 12:52 UTC, junglesub commented on src/components/Status.jsx
> +    if(event.key === 'Enter'){
엔터를 입력 받는것은 좋은 생각이나 닉네임을 입력 받고 그냥 마우스나 TAB 등으로 넘어갈 경우 state가 업데이트가 안된 상태여서 햇갈립니다.

특히 다음 칸은 클릭해야하는 input이라 엔터나 중복확인을 해야한다는 것을 알 수 있게 텍스트 등을 띄어주세요.

또한 - 닉네임이여서 중복 확인을 과연 해야하는지는 의문입니다.
필요하다고 생각하시나요?

2021-01-23 12:52 UTC, junglesub commented on src/components/Status.jsx
> +            <TextField id="home" name="home" label="거주상태" variant="outlined" onKeyPress={keyChange} /><br />
거주상태도 Dropdown 이나 ratio 체크버튼이 더 직관적이고 편리할 것 같습니다.

추천하는 아이디어가 있다면 아이콘을 이용해서 선택할 수 있게 하는 것은 어떨까요?

![image](https://user-images.githubusercontent.com/42944002/105578672-3d1a3400-5dc5-11eb-91cc-a9dad9444cd6.png)

2021-01-23 13:24 UTC, Lee-sehyun commented on src/components/AddStudent.jsx
> +    else firebase.firestore().collection('user').doc(params.uid).set(params);
수정

2021-01-23 13:24 UTC, Lee-sehyun commented on src/components/AddStudent.jsx
> +function AddStudent(params) {
수정

2021-01-23 13:24 UTC, Lee-sehyun commented on src/components/Status.jsx
> +    if(event.key === 'Enter'){
수정.
그런데 onChange로 하면 한 글자 입력할때마가 함수가 실행되어서 state가 계속 변합니다.

2021-01-23 14:19 UTC, junglesub commented on src/components/Status.jsx
> +    if(event.key === 'Enter'){
괜찮습니다.. state가 기록해주고 있다고 생각하시면 됩니다.

2021-01-25 17:10 UTC, junglesub requested changes
즉시수정요청.

2021-01-25 17:10 UTC, junglesub commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
이렇게 되면 state가 업데이트 될때마다 `listed` 가 업데이트가 됨으로 아래에 있는 `useEffect`까지 dependency로 인해 호출 됩니다. 최적화를 위해서 **즉시 수정** 요청합니다.

2021-01-25 17:10 UTC, junglesub commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
또한, 본인 uid가 아닌 users 문서를 요청할경우 권한오류가 발생합니다. 참고하세요.

2021-01-25 17:44 UTC, Lee-sehyun commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
useEffect(() => {
        const listed = firebase.firestore().collection('users').doc(match.params.uid);
        listed.get().then(doc => setState(doc.data()));
    }, [])
    이렇게 안으로 넣는 건가요?

2021-01-25 17:46 UTC, Lee-sehyun commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
일단은 path를 통해 전달한 uid로 불러왔는데, 현재 로그인 된 users가 아닌 다른 유저를 불러올 방법을 못찾아서 현재 유저의 uid로 해놓았습니다. 이것은 방법을 찾으면 바꾸도록 하겠습니다.

2021-01-25 17:46 UTC, junglesub commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
네 맞습니다.
```javascript
useEffect(() => {
firebase.firestore().collection('users').doc(match.params.uid).get().then(doc => setState(doc.data()));
}, [])
```
이렇게 한번에 묶어서 하셔도 괜찮습니다.

2021-01-25 17:47 UTC, junglesub commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
불러오는 방법은 같지만 보안상의 이유로 막아둘것입니다. 다른 유저의 정보는 필요한 정보만 가공해서 서버를 통해서 받은 생각입니다.

2021-01-25 17:48 UTC, junglesub commented on src/components/UserInfo.jsx
> +    const listed = firebase.firestore().collection('users').doc(match.params.uid);
https://www.notion.so/186561fd61374256b9005737263ad463

2021-01-26 12:13 UTC, Lee-sehyun commented on src/components/Status.jsx
> +            <TextField id="home" name="home" label="거주상태" variant="outlined" onKeyPress={keyChange} /><br />
으아으아 해냈다. 아이콘만 넣으면 됩니다. 아이콘은 뭘 싸야할지 모르겠네요.

2021-01-26 13:33 UTC, junglesub commented on src/components/Status.jsx
> +            <TextField id="home" name="home" label="거주상태" variant="outlined" onKeyPress={keyChange} /><br />
> 으아으아 해냈다. 아이콘만 넣으면 됩니다. 아이콘은 뭘 싸야할지 모르겠네요.

푸쉬해주세요

2021-01-27 16:52 UTC, junglesub requested changes

2021-01-27 16:52 UTC, junglesub commented on src/App.jsx
> +            <Route path="/user/:uid" exact component={UserInfo} />
어차피 자기 프로필만 볼 수 있기때문에 `/myprofile` 방식으로 변경해주세요.

2021-01-27 16:52 UTC, junglesub commented on src/App.jsx
> +            <Route path="/test" exact component={Test} />
마스터 머지 하기 전에 꼭 지워주세요

2021-01-27 16:52 UTC, junglesub commented on src/components/UserInfo.jsx
> +const UserInfo = ({match}) => {
![image](https://user-images.githubusercontent.com/42944002/106023775-75de4400-610a-11eb-9f4f-f2eb64099f7c.png)

오류 확인해주세요

2021-03-23 12:05 UTC, merged